export const APP_VERSION = '1.2.5'
export const APP_NAME = 'Ring Off'
export const APP_AUTHOR = 'Marcel Gruber'
export const APP_YEAR = '2026'
export const APP_REPO = 'https://github.com/m4rcelnoel/ring-off'
